server:
  port: 8090

spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8087/
        predicates:
        - Path=/emp/**
      - uri: http://localhost:8081/
        predicate:
        - Path=/temp/emp/**
